### ISSUE TITLE
Make the symfony app a fork of the standard edition and a submodule

### ISSUE THREAD

**Issue by tigitz** [b00giZm/symfony-boilerplate#1]
Hey,

First of all, it's a good initiative thanks for doing it. 

I think it would be better if the Symfony app contained in the boilerplate is a fork of the standard edition as it would help track the updates and merge them easily in the customized version. It would also help choosing which Symfony version you want to use in the future.

Also, as the customized Symfony app can be a standalone project, it probably should exist in a different git repository and link to this one via git submodule. It would allow a better decoupling.

What's your thoughts on this?

**Comment by b00gizm** [comment]
Hey Philippe,

:+1: for the idea of forking the Symfony standard edition and keeping it in a separate repository. Thanks for the idea, I totally didn't think of that.

I'm not quite sold on the submodule idea. The idea is that people should take the customized app as the base for their own project. I'm thinking that maybe it would be better to have another step in the main Dockerfile to maybe `curl` the repo's ZIP, unzip it, and copy it to the appropriate directory. Another way might be to use [Composer's `create-project`](https://getcomposer.org/doc/03-cli.md#create-project) during the build step, but I'm not familiar with it at all ;)

**Comment by tigitz** [comment]
Well, the submodule idea was to match your current way of setting up the Symfony app by forcing a unique version of it.

But you're right, the proper way would be to set up a composer project. It's not that hard to set up honestly, a bunch of docs to read and edit the `composer.json` file. Also, if it works as a fork it will take advantage of the already implemented standard edition versioning.

Are you willing to work on this enhancement soon ? I can help you with it but you'll probably need to set up things first to keep it under your namespace.

**Comment by b00gizm** [comment]
Sure, I think I'll find time today :)

**Comment by b00gizm** [comment]
@tigitz 

Sorry for being late (I just started a new job on Tuesday and needed some time to settle in), but I've finally found time.

Packagist: https://packagist.org/packages/b00gizm/symfony-boilerplate-app
Github: https://github.com/b00giZm/symfony-boilerplate-app

**Comment by tigitz** [comment]
@b00gizm, that's great! no worries 

Time to update the dockerfile now 😊

I'll make a PR next week if you don't make it first
